--Creamos la tabla Almacen 
CREATE TABLE ALMACEN(NUMERO_ALMACEN INTEGER,UBICACION_ALMACEN VARCHAR2(80),CONSTRAINT PK_NUMERO_ALMACEN PRIMARY KEY(NUMERO_ALMACEN));

--INSERTAMOS EL PRIMER REGISTRO
INSERT INTO ALMACEN VALUES(1,'PLYMOUTH');

--HACER SELECT SIMPLE 
SELECT * FROM ALMACEN;

--MI PRIMER PROCEDIMIENTO ALMACENADO 

CREATE OR REPLACE PROCEDURE HOLA(NOMBRE IN VARCHAR2)
AS
BEGIN

END;
/


